### ISSUE TITLE
Scope of the Github action

### ISSUE THREAD

**Issue by LecrisUT** [packit/actions#9]
### Description

Right now the only implementation visible is to create `srpm`s, for which the user cannot find much application for. I want to flush out what the full implementation of the GH action should be and how it could be used in the future.

Overall the idea is that packit application is the main intermediator and the default implementation if no GH action is setup, while packit GH action is the way to get fine-grained control of each operation.

### Github action
All packit actions available in the cli and packit-service should be implemented as separate actions ([rtd/actions](https://github.com/readthedocs/actions) for reference). If in the specific commit associated with a trigger, it is detected that a github workflow contains any of these GH actions, then do not trigger packit application workflow, but instead wait for the workflow to trigger them (either directly via packit cli, or indirectly by calling packit-service somehow). Otherwise default to the packit application workflows.

### Benefits
- fine-grained control of the workflow
- reduced build requests
- piggy-back onto GH action workflows (solves issues like https://github.com/packit/packit/issues/1954, https://github.com/packit/packit/issues/1987)

### Example interface

```yaml
jobs:
  normal-test:
    ...
  packaging-test:
    needs: [ normal-test ]
    steps:
      - uses: packit/actions/build_copr@latest
        with:
          targets: [ fedora-development ]
      - uses: packit/actions/test@latest
        with:
          targets: [ fedora-development ]
```

### Implementation considerations
- Should all `jobs:` in `.packit.yaml` be ignored and require them to be defined within GH action?
  (if in the commit/PR it is detected that there exists at least one `uses: packit/actions`, otherwise use default packit app logic)
- Should the packit action version be synchronized with the packit cli, or should it be adjustable via `with:version:...`?
  If the former, it would be better to move these directly in `packit/packit`, that way PRs and fork versions can be tested more easily.

### What needs to be implemented
- [x] packit-action: `srpm`
- [ ] packit-action: `build_copr`
- [ ] packit-action: `test`
- [ ] packit-action: `propose_downstream`
- [ ] select packit version
- [ ] documentation

### Workaround

- [ ] There is an existing workaround that can be used until this feature is implemented.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)
